# Generated by Django 5.1.6 on 2025-02-17 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('read_ts', models.DateTimeField()),
                ('system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hydroponicsystem')),
            ],
        ),
    ]
