# Generated by Django 5.1.6 on 2025-02-17 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_hydroponicsystem_num_of_chambers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydroponicsystem',
            old_name='activation_date',
            new_name='activation_dt',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='read_ts',
            new_name='read_dt',
        ),
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
