# Generated by Django 5.1.6 on 2025-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='num_of_chambers',
            field=models.IntegerField(default=2),
        ),
    ]
