# Generated by Django 5.1.6 on 2025-02-17 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_hydroponicsystem_num_of_chambers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='num_of_chambers',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
